### ISSUE TITLE
当有突起的时候，突起的半圆顶端线条缺失

### ISSUE THREAD

**Issue by hujxhed** [onestravel/OneBottomNavigationBar#10]

**Comment by hujxhed** [comment]
版本号是1.2.2

**Comment by eternallyjie** [comment]
一样的问题，中间凸起的部分，如果绘制分割线，圆顶端部分的分割线会缺失。版本1.2.3

**Comment by onestravel** [comment]
麻烦发个截图，我看看，如果可以的话，请将再布局中使用的设置发我一下，我测试修改一下

**Comment by eternallyjie** [comment]
> 麻烦发个截图，我看看，如果可以的话，请将再布局中使用的设置发我一下，我测试修改一下

这个issue #9 里面的图片也是有这个问题，你可以看一下。我个人布局如下

<cn.onestravel.one.navigation.androidx.OneBottomNavigationBar
            android:id="@+id/mBottomNavigationBar"
            android:layout_width="match_parent"
            android:layout_height="48dp"
            android:background="@color/white"
            android:layout_alignParentBottom="true"
            android:paddingTop="2dp"
            android:paddingBottom="2dp"
            app:oneFloatingEnable="true"
            app:oneFloatingUp="25dp"
            app:oneItemIconHeight="28dp"
            app:oneItemIconWidth="28dp"
            app:oneItemTextColor="@color/tab_selector"
            app:oneItemTextSize="@dimen/sp_10"
            app:oneItemTextTopMargin="2dp"
            app:oneItemTopLineColor="#EAEAEA"
            app:oneMenu="@menu/navigation_menu" />

另外还有使用OneBottomNavigationBar.addFragment()方法管理fragment，切换fragment的时候，会销毁前面的fragment，在重现的时候就没有数据了。请问可以支持viewpager吗？

**Comment by eternallyjie** [comment]
> 麻烦发个截图，我看看，如果可以的话，请将再布局中使用的设置发我一下，我测试修改一下

另外这两个属性设置好像没有效果

app:oneItemIconHeight
app:oneItemIconWidth

另外是否可以再支持一下中间凸出后，线是凹下去的。类似于下面这样

![image](https://user-images.githubusercontent.com/30895476/109249700-31d28200-7823-11eb-971e-ee1be72a7c63.png)

**Comment by onestravel** [comment]
请使用1.2.4-beta 版本试试，再该版本中我修复了突出时上边弧线缺失的 bug ，支持了 ViewPager

**Comment by onestravel** [comment]
> > 麻烦发个截图，我看看，如果可以的话，请将再布局中使用的设置发我一下，我测试修改一下
> 
> 另外这两个属性设置好像没有效果
> 
> app:oneItemIconHeight
> app:oneItemIconWidth
> 
> 另外是否可以再支持一下中间凸出后，线是凹下去的。类似于下面这样
> 
> ![image](https://user-images.githubusercontent.com/30895476/109249700-31d28200-7823-11eb-971e-ee1be72a7c63.png)

这个后面的版本可以考虑支持

**Comment by hujxhed** [comment]
使用1.2.4-beta 版本，我的问题解决了。

**Comment by hujxhed** [comment]
使用1.2.4-beta 版本，我的问题解决了。

**Comment by eternallyjie** [comment]
> 使用1.2.4-beta 版本，我的问题解决了。

好的，感谢

**Comment by eternallyjie** [comment]
> 使用1.2.4-beta 版本，我的问题解决了。
你好，还是会有bug。使用viewpager的时候，本来点击中间凸起的是不显示页面的，而是做其他操作。如果我当前viewpager显示的item在凸起的后面，点击凸起按钮的时候，会切换到凸起的前面那个页面。

**Comment by onestravel** [comment]
你好，我查验了这个 bug，已经修复 并重新发布，版本号为 1.2.4-beta2 , beta 属于测试版本，如有问题，我会尽快修复。谢谢！

**Comment by eternallyjie** [comment]
> 你好，我查验了这个 bug，已经修复 并重新发布，版本号为 1.2.4-beta2 , beta 属于测试版本，如有问题，我会尽快修复。谢谢！

好的，感谢。我本来是在OnItemSelectedListener里面return true来避免的。
