### ISSUE TITLE
 AAPT: error: duplicate value for resource 'attr/itemIconTint' with config ''.

### ISSUE THREAD

**Issue by wenlla** [onestravel/OneBottomNavigationBar#3]
AAPT: error: duplicate value for resource 'attr/itemIconTint' with config ''.
AAPT: error: resource previously defined here.
AAPT: error: duplicate value for resource 'attr/itemTextColor' with config ''.

/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml: AAPT: error: file failed to compile.

使用android studio 运行后的结果

**Comment by onestravel** [comment]
> AAPT: error: duplicate value for resource 'attr/itemIconTint' with config ''.
> AAPT: error: resource previously defined here.
> AAPT: error: duplicate value for resource 'attr/itemTextColor' with config ''.
> 
> /app/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml: AAPT: error: file failed to compile.
> 
> 使用android studio 运行后的结果

你好，这个错误是引用的两个包中的属性名称冲突导致，麻烦您排查一下，看和哪个sdk冲突，如果是直接源码依赖引入，您可以更改一下属性，如果是jitpack引入，我后续会对属性名进行优化，尽量避免冲突，谢谢支持！

**Comment by 15768093606** [comment]
AAPT: error: attribute floatingEnable (aka com.fq.tolalacilent:floatingEnable) not found.

**Comment by onestravel** [comment]
already fixed
