### ISSUE TITLE
当Item有突出的时候无法绘制分割线

### ISSUE THREAD

**Issue by ChinaLike** [onestravel/OneBottomNavigationBar#5]
当Item有突出的时候无法绘制分割线

**Comment by onestravel** [comment]
你好，特别感谢提出问题，我已经对该问题进行验证并修复，目前针对该问题发布了1.2.2版本，您可以升级一下sdk版本尝试使用，后续如果有什么问题，欢迎沟通。
implementation 'cn.onestravel.one:one_bottom_navigationbar:1.2.2'

**Comment by onestravel** [comment]
> 当Item有突出的时候无法绘制分割线

你好，特别感谢提出问题，我已经对该问题进行验证并修复，目前针对该问题发布了1.2.2版本，您可以升级一下sdk版本尝试使用，后续如果有什么问题，欢迎沟通。
implementation 'cn.onestravel.one:one_bottom_navigationbar:1.2.2'
