### ISSUE TITLE
属性丢失

### ISSUE THREAD

**Issue by zhaohuanhui** [onestravel/OneBottomNavigationBar#8]
找不到属性app:floatingEnable="true",app:floatingUp="25dp"

**Comment by onestravel** [comment]
> 找不到属性app:floatingEnable="true",app:floatingUp="25dp"

并不是属性丢失，因解决属性冲突，更改了属性名称，已经修改过文档，请参考修改属性名称

![image](https://user-images.githubusercontent.com/15831739/97670703-c6b9ae80-1ac1-11eb-86de-14ee3f9162db.png)
