### ISSUE TITLE
打开界面，手机锁屏后再打开会向上移动

### ISSUE THREAD

**Issue by zhaohuanhui** [onestravel/OneBottomNavigationBar#9]
打开界面，手机锁屏后再打开会向上移动

**Comment by zhaohuanhui** [comment]
fragment

**Comment by zhaohuanhui** [comment]
使用

**Comment by onestravel** [comment]
> 打开界面，手机锁屏后再打开会向上移动

我看下图片效果，我这里测试没有问题，我觉得如果是整个 NavigationBar 上移，应该是你的布局问题

**Comment by 13570524658** [comment]
![Uploading IMG_4625.JPG…]()

**Comment by zhaohuanhui** [comment]
![IMG_4625](https://user-images.githubusercontent.com/25172521/97830647-a29bde80-1d08-11eb-8260-0e0d72094fed.JPG)

**Comment by zhaohuanhui** [comment]
![IMG_4626](https://user-images.githubusercontent.com/25172521/97830884-674ddf80-1d09-11eb-8396-a60b242cf19a.JPG)

**Comment by zhaohuanhui** [comment]
而且 setOnItemSelectedListener 进入fragment的时候就执行了。。。。我写在 onViewCreated

**Comment by zhaohuanhui** [comment]
不支持repalce 吗？

**Comment by zhaohuanhui** [comment]
我自定义了一个。没问题。你这个不支持。

**Comment by onestravel** [comment]
> 我自定义了一个。没问题。你这个不支持。

oneBottomLayout.isReplace = true
打开这个开关是支持 replace 的

**Comment by onestravel** [comment]
> > 打开界面，手机锁屏后再打开会向上移动
> 应该是布局的问题，导致位置测量出现偏差，我看到有一张图片上导航栏直接覆盖在了主界面上边，这应该是布局错误你可以参考一下 demo 中的 MainActivity的布局方式

**Comment by onestravel** [comment]
以上问题已解决，请使用 1.2.4-beta 版本
